-- ReadPanda schema bootstrap script
-- Safe to run multiple times in local development.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'login_type_enum'
          AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.login_type_enum AS ENUM ('email', 'social_google', 'ldap');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.users
(
    uuid uuid PRIMARY KEY,
    username character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(300),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    isactive boolean DEFAULT true,
    login_type public.login_type_enum,
    google_sub text,
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.preferences
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subgenre character varying(50) NOT NULL,
    description text,
    genre character varying(50)
);

CREATE TABLE IF NOT EXISTS public.user_preferences
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    preferences json,
    user_id uuid NOT NULL,
    CONSTRAINT user_preference_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (uuid)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.books
(
    book_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid,
    title character varying(50),
    description text,
    subgenre character varying(50),
    genre character varying(50),
    cover_image_url text,
    manuscript_url text,
    views integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status integer DEFAULT 0,
    earnings numeric DEFAULT 0,
    CONSTRAINT user_books_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (uuid)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    message json,
    CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (uuid)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.refresh_tokens
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    token text NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (uuid)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_userpreferences_userid
    ON public.user_preferences (user_id);

CREATE INDEX IF NOT EXISTS idx_books_userid
    ON public.books (user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id
    ON public.notifications (user_id);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at
    ON public.refresh_tokens (expires_at);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id
    ON public.refresh_tokens (user_id);
